let form = document.getElementById("form");
form.style.border = "thin solid #040404";
form.style.textAlign = "center";
form.style.width = "50%";
form.style.borderRadius = "10px";
form.style.padding = "2%";
form.style.marginLeft = "auto";
form.style.marginRight = "auto";
form.style.fontFamily = "Open Sans, Helvetica Neue, sans-serif";